### ISSUE TITLE
Redirection FAIL while Sign In: signInWithRedirect fails to redirect on localhost due to third-party storage access blocking

### ISSUE THREAD

**Issue by vin-dKR** [aladinyo/ChatPlus#1]
### Issue Description

I was experiencing an issue with `signInWithRedirect` on `localhost` when using Firebase SDK. When I tried to log in, I was not redirected to my app after successful authentication.

### Steps to Reproduce

1. hit this in the search bar - chrome://flags/#third-party-storage-partitioning 
![image](https://github.com/aladinyo/ChatPlus/assets/109779300/74519a74-0291-458d-bcec-7c6538f8d075)

2. disable Third-party Storage Partitioning 
![image](https://github.com/aladinyo/ChatPlus/assets/109779300/bef42348-497e-4c7f-a662-c9d03169752f)

3. after relaunching the browser if it still not working then go to this 
![image](https://github.com/aladinyo/ChatPlus/assets/109779300/c39f0c3f-ae72-4418-90ce-c28e7ba06a66)

4. in Cookies and Site data allow third-party cookies 
![image](https://github.com/aladinyo/ChatPlus/assets/109779300/26a57d4c-8b23-4dc8-857b-0bc961ea77d9)

## Reference 
https://stackoverflow.com/questions/77270210/firebase-onauthstatechanged-user-returns-null-when-on-localhost

https://firebase.google.com/docs/auth/web/redirect-best-practices

**Comment by aladinyo** [comment]
Thank so much for this issue, you provided detailed explanation of the solution
